### ISSUE TITLE
cephci failures; AttributeError: 'CephVMNode' object has no attribute 'name'

### ISSUE THREAD

**Issue by julpark-rh** [red-hat-storage/ceph#109]

**Comment by julpark-rh** [comment]
Possible solutions:
In cephci/mita/openstack.py , try changing to cci4,5,6,7
(self.vm_network = "provider_net_cci_8")

**Comment by sunilkumarn417** [comment]
@julpark-rh, can you create this issue in cephci, if it is cephci issue?

**Comment by v26i** [comment]
https://github.com/red-hat-storage/cephci/issues/154
