### ISSUE TITLE
rgw tests need nfs-ganesha-selinux rpm installed in teuthology

### ISSUE THREAD

**Issue by kalebskeithley** [red-hat-storage/ceph#39]
the nfs-ganesha rpm does not have a dependency on the nfs-ganesha-selinux rpm, it must be explicitly installed.

FWIW I've already had a conversation with Tejas who said he would work on getting this resolved.

**Comment by kalebskeithley** [comment]
any update on this?

**Comment by rakeshgm** [comment]
The first NFS test http://pulpito.ceph.redhat.com/rakesh-2020-05-05_04:43:13-rgw:nfs-ganesha-rgw-v2-nautilus-distro-basic-pluto/ - got SELinux denials on `ganesha.nfsd` 
so after whitelisting, I have been getting these SELinux error `ceph-mon`, `ceph-mgr`. 

These tests are on builds on latest ceph-composes, i.e after Thomas repinned 4.1 builds with selinux enabled.

**Comment by kalebskeithley** [comment]
that isn't the ask.

Has the testing infra been updated to install the nfs-ganesha-selinux RPM?

**Comment by rakeshgm** [comment]
@kalebskeithley we are not able to find nfs-ganesha-selinux rpm for RHEL 7.x.  And because of this @TejasC88 had written a mail to you regarding the same. 
If you could provide the location of the package. I would install it in the infra.

**Comment by kalebskeithley** [comment]
http://download-node-02.eng.bos.redhat.com/brewroot/packages/nfs-ganesha/2.8.3/7.el7cp/noarch/

**Comment by rakeshgm** [comment]
Added the installation here [73](https://github.com/red-hat-storage/ceph/pull/73)

**Comment by rakeshgm** [comment]
@TejasC88 and @kalebskeithley  can we close this issue.

**Comment by kalebskeithley** [comment]
lgtm I think you can close it.

Thanks
